kind: pipeline
type: docker
name: docker-test

platform:
  os: linux
  arch: amd64
node:
  arch: s390x

steps:
- name: build
  image: bash:alpine3.14
  commands:
  - ls -la
  - echo "This is a test"

- name: step to fail
  image: bash:alpine3.14
  commands:
  - unknown_command

- name: slack
  image: s390x-slack:latest
  pull: never
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general
    link_names: true
    template: >
        build {{build.number}} failed. It took {{since build.started}} {{build.link}}
  when:
    status:
      - failure
