kind: pipeline
type: docker
name: docker-test

environment:
  registry: public.ecr.aws/b3e3i8k2

#node:
  #rancher_enterprise: true

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: publish
  image: luistt/drone-images:v0.0.7-docker-s390x #plugins/docker
  #environment:
    #resgistry: $REGISTRY
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: test/Dockerfile
    tag: test
    registry: public.ecr.aws/b3e3i8k2 
    repo: public.ecr.aws/b3e3i8k2/test
    region: us-east-1
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: certs
  host:
    path: /var/lib/drone
