kind: pipeline
type: docker
name: docker-test

environment:
  registry: public.ecr.aws/b3e3i8k2

#node:
  #rancher_enterprise: true

platform:
  os: linux
  arch: amd64

#node:
  #arch: s390x

steps:
- name: publish
  image: luistt/drone-images:enterprise-v0.0.1 #plugins/docker
  environment:
    REGISTRY: public.ecr.aws/b3e3i8k2
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY 
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: test/Dockerfile
    tag: test
    registry: public.ecr.aws/b3e3i8k2 
    repo: public.ecr.aws/b3e3i8k2/test
    region: us-east-1
    #username:
      #from_secret: docker_username
    #password:
      #from_secret: docker_password

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: certs
  host:
    path: /var/lib/drone
